name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Versi terbaru

      - name: Setup Java
        uses: actions/setup-java@v4 # Versi terbaru
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-codesign

      - name: Upload APK Result
        uses: actions/upload-artifact@v4 # Versi terbaru
        with:
          name: livego-apk
          path: build/app/outputs/flutter-apk/app-release.apk
