name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Fresh Android Project
        run: |
          # Menghapus sisa-sisa lama dan membuat project baru yang bersih
          rm -rf android
          flutter create --platforms android --org com.yudhanugraha .
          
      - name: Inject Google TV Support
        run: |
          # Menambahkan kategori Leanback agar muncul di Google TV
          sed -i '/android.intent.category.LAUNCHER/a \                <category android:name="android.intent.category.LEANBACK_LAUNCHER" />' android/app/src/main/AndroidManifest.xml

      - name: Build APK (Perintah yang sudah diperbaiki)
        run: flutter build apk --release

      - name: Upload APK Result
        uses: actions/upload-artifact@v4
        with:
          name: livego-apk
          path: build/app/outputs/flutter-apk/app-release.apk
